Publish up-esb on pypi
aiplan4eu/embedded-systems-bridge pull request #28
Opened 2023-06-15 13:22 UTC by jarkenau

Summary:
 - Add script to build and upload the embedded system bridge to PyPI
 - Add status badges in README

In order to publish a package, the following steps are needed.

1. Update the version in the `pyproject.toml` (PyPi will block uploads with an already present version number) https://github.com/aiplan4eu/embedded-systems-bridge/blob/ae1e7da203762a606ee6953c90ae935920bb6ba4/pyproject.toml#L32
2. Run the `push-pypi.sh` script and login with your PyPi credentials for authentication. 

Alternatively, I cloud also add this into the GitHub pipeline and automatically update the package on a new [Release](https://github.com/aiplan4eu/embedded-systems-bridge/releases) .

Closes #24

2023-06-20 09:21 UTC, jarkenau commented
Hi @franklinselva, could you take a look, if this approach fit's for you?

2023-06-21 10:24 UTC, franklinselva commented
Hi @jarkenau, Thanks for the changes. As for the steps mentioned,

1. Currently we have a GitHub job that updates the version of the package automatically. Rebasing the work from [master](https://github.com/aiplan4eu/embedded-systems-bridge) branch should give you the recent version. 
2. I would also recommend moving to GitHub actions since we already have a [workflow](https://github.com/aiplan4eu/embedded-systems-bridge/blob/master/.github/workflows/deploy.yml) for this purpose. We can publish only if there is a version bump from the existing jobs.

To enable github actions, I think we might need to setup `PYPI_API_TOKEN` to the secrets of the current repository. But I believe only @sebastianstock should be able to setup the token currently.

2023-06-22 13:11 UTC, jarkenau commented
Sorry for all the force pushing (and probably the e-mails). But I have to push the code to GitHub to test if the actions work. 
If @sebastianstock adds the `PYPI_API_TOKEN`  to the repo (tutorial for that [here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github))  the actions should now automatically release a new version after a successful PR.

2023-06-23 08:32 UTC, sebastianstock commented
> Sorry for all the force pushing (and probably the e-mails). But I have to push the code to GitHub to test if the actions work. If @sebastianstock adds the `PYPI_API_TOKEN` to the repo (tutorial for that [here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github)) the actions should now automatically release a new version after a successful PR.

Done.

2023-06-23 08:58 UTC, jarkenau commented
@franklinselva I now integrated the publishing into the `deploy` action. From my side, it could be merged now.

2023-06-23 08:58 UTC, franklinselva requested changes
Looks good to me. I have requested a single change to trigger the job only on merges.

2023-06-23 08:58 UTC, franklinselva commented on .github/workflows/deploy.yml
> -    if: github.event.pull_request.merged == true
I think we may still need this condition since pull requests can be closed without merging into the master branch.

2023-06-23 09:06 UTC, franklinselva approved these changes

2023-06-23 09:07 UTC, merged